
task:
  name: Docker Build
  container:
    image: gcr.io/kaniko-project/executor:debug
  build_script: executor --destination=cirrus:local --tarPath=/tmp/image.tar --context=$CIRRUS_WORKING_DIR --verbosity=debug